In [3]:
a = int(input("enter the first number:"))
b = int(input("enter the second number:"))
try: 
    c = a/b
    print("answer:",c)
    
except:
    print("cannot perform the operation!!!")
print('thank you for using this program')

enter the first number:4
enter the second number:0
cannot perform the operation!!!
thank you for using this program


In [19]:

try:
    a = int(input("enter the number:"))
    print(f"the table of {a} is")
    for i in range(1,11):
        print(f"{int(a)} X {i} = {int(a)*i}")
except:
    print("can not perform the operation!!!")
    
    


enter the number:gf
can not perform the operation!!!


# file handling

In [8]:
class computer:
    
    
    def __init__(self,cpu,ram):
        self.ram = ram
        self.cpu = cpu
    
    def config(self):
        print(self.cpu,self.ram)
com1 = computer("cdsc","dfsdc")

com1.config()
        

cdsc dfsdc


In [1]:
#importing os
import os
os.getcwd()#checking current directory

'C:\\Users\\Jay\\Desktop\\internship\\AI-ML_traning'

In [4]:
os.chdir('C:\\Users\\Jay\\Desktop\\internship\\data hamdling')# assigning new directrory

In [17]:
f = open('file.txt','w')#creating a file in the newly assigned directory
f.write('I m awsome')#writing function
f.write('\nnevertheless i still study.') #writing function
f.close()
print('the assigned task is completed')

the assigned task is completed


In [18]:
#appending text in python file
with open('file.txt','a') as f:
    f.write('\nwork hard despite your intellect')
    print('the assigned task is completed')

the assigned task is completed


In [22]:
#read ing the txt file
with open('file.txt','r') as f:
    pa = f.read()
    print(pa)
    

I m awsome
nevertheless i still study.
work hard despite your intellect


In [26]:
#slicing the read command
with open('file.txt','r') as f:
    par = f.read(23)
    print(par)
    

I m awsome
nevertheless


In [25]:
with open('file1.txt','x') as g:
    g.write('one piece is real')
    print('assigned task done')
    

assigned task done


In [24]:
os.remove('file1.txt')
print("file deleted")

file deleted


In [35]:
# L = [1.5 ,'Python', False] 
# T = (1.2, 'Java', True) 
# for i in range(len(L)): 
#   if L[i]: 
#      L[i] = L[i] + T[i] 
# #   else: 
# #      T[i] = L[i] + T[i] 
 
# print(L) 

[2.7, 'PythonJava', False]


In [36]:
import copy
list1 = [10, 20, 30, ['A' , 'B' , 'C']]
list2 = list1.copy()
list3 = copy.deepcopy(list1)
list1[3][1] = 0000
list1[1] = 0000
print(list1) 
print(list2)
print(list3)

[10, 0, 30, ['A', 0, 'C']]
[10, 20, 30, ['A', 0, 'C']]
[10, 20, 30, ['A', 'B', 'C']]


In [38]:
class Vehicle :
      def __init__(brand):
        print('Brand:','Ford')
Vehicle()

Brand: Ford


In [49]:
def say(p ,q=42,r=5 , s=28):
  print(' p :',p,' q :',q,' r :',r,' s :',s)
say(48,(45),56,s=30)

 p : 48  q : 45  r : 56  s : 30


In [50]:
0.1 +0.2

0.30000000000000004

In [62]:
import numpy as np
import copy 


In [71]:
a1 = np.array([1,5])

a = np.array([1,3,4,5,6])
a =np.concatenate((a, a1))
b= copy.copy(a)
c=copy.deepcopy(a)


In [72]:
a

array([1, 3, 4, 5, 6, 1, 5])

In [65]:
b

array([1, 3, 4, 5, 6])

In [66]:
b[1]=2

In [67]:
b

array([1, 2, 4, 5, 6])

In [68]:
a

array([1, 3, 4, 5, 6])

In [69]:
c

array([1, 3, 4, 5, 6])

In [73]:
# 
q = 0.2 + 0.1
q


0.30000000000000004

In [74]:
from decimal import Decimal

In [75]:
r = Decimal('0.1') + Decimal('0.2')
r

Decimal('0.3')